"""The building's skin where the drawing leaves it open, for the 3D map.

    python scripts/build_envelope.py

The architects' drawing gives the walls of rooms; along the edges of each
floor it often shows glazing, rails or retaining walls only as lines that
did not come through as walls. Walked round in 3D, those edges are holes
onto the street or into a void. This finds every stretch of a floor's edge
that no wall covers and says what belongs there:

  glass  the outside of the ground and first floors: a curtain wall,
         except across the two entrances, which stay open as doorways;
  rail   the edge of a void, upstairs: a glass balustrade;
  solid  the outside of the basement: a concrete retaining wall.

Writes lib/venue-envelope.ts, in the 3D scene's frame (metres, x east, z
south), from lib/venue-3d-scene.ts.
"""

import json
from pathlib import Path

from shapely.geometry import LineString, box
from shapely.ops import unary_union

ROOT = Path(__file__).resolve().parent.parent
SCENE_TS = ROOT / "lib" / "venue-3d-scene.ts"
OUT = ROOT / "lib" / "venue-envelope.ts"

# A wall this close to an edge counts as standing on it.
NEAR = 0.35
# Gaps shorter than this are joints in the drawing, not openings.
MIN_GAP = 0.6
# Slabs that meet within this are one floor, not two with a seam.
SEAM = 0.06


def load_scene() -> dict:
    s = SCENE_TS.read_text(encoding="utf-8")
    i = s.index("export const SCENE")
    j = s.index("{", i)
    k = s.index(" as const", j)
    return json.loads(s[j:k])


def rect(x: float, z: float, w: float, d: float):
    return box(x - w / 2, z - d / 2, x + w / 2, z + d / 2)


def entrance_spans(scene: dict) -> list:
    """Each entrance as a short line across the edge it opens in."""
    spans = []
    for e in scene["entrances"]:
        half = e["w"] / 2
        if e["facing"] in ("east", "west"):
            spans.append(box(e["x"] - 3, e["z"] - half, e["x"] + 3, e["z"] + half))
        else:
            spans.append(box(e["x"] - half, e["z"] - 3, e["x"] + half, e["z"] + 3))
    return spans


def lines(geom) -> list:
    if geom.is_empty:
        return []
    if geom.geom_type == "LineString":
        return [geom]
    return [g for g in getattr(geom, "geoms", []) if g.geom_type == "LineString"]


def main() -> None:
    scene = load_scene()
    doors = unary_union(entrance_spans(scene))
    out: dict[str, list] = {}
    for floor, data in scene["floors"].items():
        slab = unary_union([rect(s["x"], s["z"], s["w"], s["d"]) for s in data["slabs"]])
        slab = slab.buffer(SEAM, join_style=2).buffer(-SEAM, join_style=2)
        walls = unary_union(
            [rect(w["x"], w["z"], w["w"] + 2 * NEAR, w["d"] + 2 * NEAR) for w in data["walls"]]
        )
        polys = [slab] if slab.geom_type == "Polygon" else list(slab.geoms)
        segs = []
        for poly in polys:
            rings = [(poly.exterior, "outside")] + [(r, "void") for r in poly.interiors]
            for ring, where in rings:
                pts = list(ring.coords)
                for a, b in zip(pts, pts[1:]):
                    edge = LineString([a, b])
                    for piece in lines(edge.difference(walls)):
                        if piece.length < MIN_GAP:
                            continue
                        if where == "void":
                            kinds = [("rail", piece)]
                        elif floor == "basement":
                            kinds = [("solid", piece)]
                        elif floor != "ground":
                            # Upstairs the facade is glass all along: an
                            # entrance below it is no opening up here.
                            kinds = [("glass", piece)]
                        else:
                            # The entrances stay open; glass either side.
                            kinds = [("door", g) for g in lines(piece.intersection(doors)) if g.length >= MIN_GAP]
                            kinds += [("glass", g) for g in lines(piece.difference(doors)) if g.length >= MIN_GAP]
                        for kind, g in kinds:
                            (x1, z1), (x2, z2) = g.coords[0], g.coords[-1]
                            segs.append({"k": kind, "a": [round(x1, 2), round(z1, 2)], "b": [round(x2, 2), round(z2, 2)]})
        out[floor] = segs
        tally = {}
        for sgm in segs:
            tally[sgm["k"]] = tally.get(sgm["k"], 0) + 1
        print(floor, tally)

    OUT.write_text(
        "/**\n"
        " * Generated by scripts/build_envelope.py from lib/venue-3d-scene.ts: the\n"
        " * stretches of each floor's edge that the drawing leaves without a wall,\n"
        " * and what stands there. glass: a curtain wall; door: an entrance, left\n"
        " * open; rail: a glass balustrade at a void; solid: a basement wall.\n"
        " */\n\n"
        "export type EnvelopeKind = \"glass\" | \"door\" | \"rail\" | \"solid\";\n\n"
        "export const ENVELOPE: Record<\"ground\" | \"first\" | \"basement\", readonly { k: EnvelopeKind; a: readonly [number, number]; b: readonly [number, number] }[]> = "
        + json.dumps(out, separators=(",", ":"))
        + " as const;\n",
        encoding="utf-8",
    )
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
